import Head from "next/head"
import Image from "next/image"
import { demoData } from "@/demoData"
import BulletinCard from "@/components/BulletinCard"

export default function Home() {
  return (
    <>
      <Head>
        <title>oneClick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-6xl mx-auto my-8">
        <h1 className="px-7 text-left py-3 h-fit w-fit bg-[#086DC9] rounded-t-lg text-xl font-bold text-white">
          Updates / News
        </h1>
        <div className="max-w-6xl space-y-8 bg-black/25 p-12 rounded-b-xl rounded-tr-xl">
          {demoData.map((data) => (
            <BulletinCard
              key={data.id}
              title={data.title}
              description={data.description}
              file={data.file}
            />
          ))}
        </div>
      </div>
    </>
  )
}
